[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
CORS_ORIGIN = "https://hot-wheels-manager.vercel.app,https://hot-wheels-manager-jfsn91o9q-antonio-martnez-s-projects.vercel.app"
MONGODB_URI = "${{MONGODB_URI}}"
