[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd backend && npm run build"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
